openapi: 3.0.0
info:
  title: Product Service
  description: Apo for product service
  version: 1.0.0

servers:
  - url: https://wy7ppwbbh0.execute-api.eu-west-1.amazonaws.com/dev

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        age:
          type: number
        price:
          type: number
        breed:
          type: string
        imgLink:
          type: string
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

paths:
  /product:
    get:
      tags:
        - Products
      summary: Get all products
      description: Gets all products
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        401:
          $ref: "#/components/responses/UnauthorizedError"
  /product/{productId}:
    parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Product
      summary: Get product by ID
      description: Gets a product by ID
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        404:
          description: Cat not found
